; "$Id: ATmega328P_uOS_Commands.h,v 1.1 2026/01/26 17:47:34 administrateur Exp $"

#define	CHAR_COMMAND_REC		'<'
#define	CHAR_COMMAND_SEND		'>'
#define	CHAR_COMMAND_MORE		'-'
#define	CHAR_COMMAND_PLUS		'+'
#define	CHAR_COMMAND_UNKNOWN	'?'

#define	FLG_TEST_COMMAND_TYPE_MSK				MSK_BIT0
#define	FLG_TEST_COMMAND_IN_PROGRESS_MSK		MSK_BIT1
#define	FLG_TEST_COMMAND_MORE_MSK				MSK_BIT2
#define	FLG_TEST_COMMAND_PLUS_MSK				MSK_BIT3
#define	FLG_TEST_COMMAND_ERROR_MSK				MSK_BIT4
#define	FLG_TEST_PROGRAMING_ERROR_MSK			MSK_BIT5
#define	UOS_FLG_TEST_EEPROM_ERROR_MSK			MSK_BIT6
#define	FLG_TEST_CONFIG_ERROR_MSK				MSK_BIT7

#define	FLG_TEST_COMMAND_TYPE_IDX				IDX_BIT0
#define	FLG_TEST_COMMAND_IN_PROGRESS_IDX		IDX_BIT1
#define	FLG_TEST_COMMAND_MORE_IDX				IDX_BIT2
#define	FLG_TEST_COMMAND_PLUS_IDX				IDX_BIT3
#define	FLG_TEST_COMMAND_ERROR_IDX				IDX_BIT4
#define	FLG_TEST_PROGRAMING_ERROR_IDX			IDX_BIT5
#define	FLG_TEST_EEPROM_ERROR_IDX				IDX_BIT6
#define	FLG_TEST_CONFIG_ERROR_IDX				IDX_BIT7

.dseg

UOS_G_TEST_FLAGS:		.byte		1

UOS_G_TEST_COMMAND_TYPE:	.byte		1
UOS_G_TEST_VALUE_MSB:		.byte		1
UOS_G_TEST_VALUE_LSB:		.byte		1
UOS_G_TEST_VALUE_MSB_MORE:	.byte		1
UOS_G_TEST_VALUE_LSB_MORE:	.byte		1

G_TEST_VALUE_DEC_MSB:		.byte		1
G_TEST_VALUE_DEC_LSB:		.byte		1

UOS_G_TEST_VALUES_IDX_WRK:	.byte		1				; Index sur les valeurs de 'G_TEST_VALUES_ZONE' (travail)
UOS_G_TEST_VALUES_IDX:		.byte		1				; Index sur les valeurs de 'G_TEST_VALUES_ZONE' (disponible)
UOS_G_TEST_VALUES_ZONE:		.byte		(2 * 64)		; Page de 64 mots

; End of file
